// <auto-generated />
using System;
using CinemaDashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaDashboard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260425175308_update")]
    partial class update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CinemaDashboard.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Famous Egyptian action actor",
                            Img = "1.jpg",
                            Name = "Ahmed Ezz",
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Renowned Egyptian drama actress",
                            Img = "2.jpg",
                            Name = "Mona Zaki",
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Versatile Egyptian movie star",
                            Img = "3.jpg",
                            Name = "Karim Abdel Aziz",
                            Status = true
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Award-winning actress",
                            Img = "4.jpg",
                            Name = "Hend Sabry",
                            Status = true
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Top Egyptian comedy actor",
                            Img = "5.jpg",
                            Name = "Ahmed Helmy",
                            Status = true
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Acclaimed drama actress",
                            Img = "6.jpg",
                            Name = "Nelly Karim",
                            Status = false
                        });
                });

            modelBuilder.Entity("CinemaDashboard.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookedAt = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "Ahmed Ali",
                            CustomerPhone = "01012345678",
                            MovieId = 1,
                            Seats = 2
                        },
                        new
                        {
                            Id = 2,
                            BookedAt = new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "Sara Mohamed",
                            CustomerPhone = "01198765432",
                            MovieId = 2,
                            Seats = 1
                        },
                        new
                        {
                            Id = 3,
                            BookedAt = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "Khaled Hassan",
                            CustomerPhone = "01234567890",
                            MovieId = 3,
                            Seats = 3
                        },
                        new
                        {
                            Id = 4,
                            BookedAt = new DateTime(2025, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "Ahmed Ali",
                            CustomerPhone = "01012345678",
                            MovieId = 5,
                            Seats = 2
                        },
                        new
                        {
                            Id = 5,
                            BookedAt = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "Nour Tarek",
                            CustomerPhone = "01556677889",
                            MovieId = 6,
                            Seats = 4
                        });
                });

            modelBuilder.Entity("CinemaDashboard.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "High energy action movies",
                            Name = "Action",
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            Description = "Emotional and story-driven",
                            Name = "Drama",
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            Description = "Light-hearted and funny",
                            Name = "Comedy",
                            Status = true
                        },
                        new
                        {
                            Id = 4,
                            Description = "Scary and thrilling movies",
                            Name = "Horror",
                            Status = false
                        },
                        new
                        {
                            Id = 5,
                            Description = "Science fiction and futurism",
                            Name = "Sci-Fi",
                            Status = true
                        });
                });

            modelBuilder.Entity("CinemaDashboard.Models.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Cinemas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Biggest cinema in Cairo",
                            Img = "1.jpg",
                            Name = "Grand Cinema Cairo",
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            Description = "Located in Alexandria",
                            Img = "2.jpg",
                            Name = "Stars Cinema Alex",
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            Description = "Modern screens in Giza",
                            Img = "3.jpg",
                            Name = "Nova Screens Giza",
                            Status = true
                        },
                        new
                        {
                            Id = 4,
                            Description = "Family-friendly cinema",
                            Img = "4.jpg",
                            Name = "CinePlex Maadi",
                            Status = false
                        },
                        new
                        {
                            Id = 5,
                            Description = "Premium experience",
                            Img = "5.jpg",
                            Name = "Royal Cinema Heliopolis",
                            Status = true
                        });
                });

            modelBuilder.Entity("CinemaDashboard.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CinemaId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CinemaId = 1,
                            DateTime = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Epic action in the desert",
                            MainImg = "1.jpg",
                            Name = "Desert Storm",
                            Price = 120m,
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CinemaId = 2,
                            DateTime = new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A love story gone wrong",
                            MainImg = "2.jpg",
                            Name = "Broken Hearts",
                            Price = 95m,
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CinemaId = 3,
                            DateTime = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Non-stop comedy",
                            MainImg = "3.jpg",
                            Name = "Laugh Factory",
                            Price = 80m,
                            Status = true
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CinemaId = 4,
                            DateTime = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Horror thriller",
                            MainImg = "4.jpg",
                            Name = "Dark Shadows",
                            Price = 100m,
                            Status = false
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CinemaId = 5,
                            DateTime = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sci-fi adventure",
                            MainImg = "5.jpg",
                            Name = "Galaxy Quest",
                            Price = 150m,
                            Status = true
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CinemaId = 1,
                            DateTime = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Action in the streets",
                            MainImg = "6.jpg",
                            Name = "City of Fire",
                            Price = 110m,
                            Status = true
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CinemaId = 2,
                            DateTime = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Emotional family drama",
                            MainImg = "7.jpg",
                            Name = "Silent Tears",
                            Price = 90m,
                            Status = true
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CinemaId = 3,
                            DateTime = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Family comedy for all ages",
                            MainImg = "8.jpg",
                            Name = "Just Kidding",
                            Price = 75m,
                            Status = true
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            CinemaId = 4,
                            DateTime = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Supernatural horror",
                            MainImg = "9.jpg",
                            Name = "The Awakening",
                            Price = 105m,
                            Status = false
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            CinemaId = 5,
                            DateTime = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Space exploration epic",
                            MainImg = "10.jpg",
                            Name = "Beyond the Stars",
                            Price = 160m,
                            Status = true
                        });
                });

            modelBuilder.Entity("CinemaDashboard.Models.MovieActor", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("MovieActors");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 1,
                            ActorId = 3
                        },
                        new
                        {
                            MovieId = 2,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 2,
                            ActorId = 4
                        },
                        new
                        {
                            MovieId = 3,
                            ActorId = 5
                        },
                        new
                        {
                            MovieId = 4,
                            ActorId = 3
                        },
                        new
                        {
                            MovieId = 5,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 6,
                            ActorId = 1
                        },
                        new
                        {
                            MovieId = 7,
                            ActorId = 2
                        },
                        new
                        {
                            MovieId = 8,
                            ActorId = 5
                        },
                        new
                        {
                            MovieId = 9,
                            ActorId = 6
                        },
                        new
                        {
                            MovieId = 10,
                            ActorId = 3
                        });
                });

            modelBuilder.Entity("CinemaDashboard.Models.MovieSubImage", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MovieId", "Img");

                    b.ToTable("MovieSubImages");
                });

            modelBuilder.Entity("CinemaDashboard.Models.Booking", b =>
                {
                    b.HasOne("CinemaDashboard.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaDashboard.Models.Movie", b =>
                {
                    b.HasOne("CinemaDashboard.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaDashboard.Models.Cinema", "Cinema")
                        .WithMany()
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("CinemaDashboard.Models.MovieActor", b =>
                {
                    b.HasOne("CinemaDashboard.Models.Actor", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaDashboard.Models.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaDashboard.Models.MovieSubImage", b =>
                {
                    b.HasOne("CinemaDashboard.Models.Movie", "Movie")
                        .WithMany("SubImages")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaDashboard.Models.Movie", b =>
                {
                    b.Navigation("MovieActors");

                    b.Navigation("SubImages");
                });
#pragma warning restore 612, 618
        }
    }
}
